version: '3.9'
services:
  api:
    build: ./backend
    container_name: bltpsk-simple-api
    ports:
      - 3001:3001
  app:
    build:
      context: .
      args:
        - API_BASE_URL=${API_BASE_URL:-http://localhost:3001/}
    container_name: nltpsk-nextjs-app
    ports:
      - 3000:3000