import React from 'react';
import { Roboto } from 'next/font/google';

import './globals.css';
import { StoreProvider } from '@/services/store-provider';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={roboto.variable}>
      <body>
        <Header />
        <StoreProvider>{children}</StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
